<?php 
$ukTowns = array(
    'Bedfordshire' => 'Bedfordshire',
    'Berkshire' => 'Berkshire',
    'Buckinghamshire' => 'Buckinghamshire',
    'Cambridgeshire' => 'Cambridgeshire',
    'Cheshire' => 'Cheshire',
    'Cornwall' => 'Cornwall',
    'Cumberland' => 'Cumberland',
    'Derbyshire' => 'Derbyshire',
    'Devon' => 'Devon',
    'Dorset' => 'Dorset',
    'Durham' => 'Durham',
    'East Yorkshire' => 'East Yorkshire',
    'Essex' => 'Essex',
    'Gloucestershire' => 'Gloucestershire',
    'Hampshire' => 'Hampshire',
    'Herefordshire' => 'Herefordshire',
    'Hertfordshire' => 'Hertfordshire',
    'Huntingdonshire' => 'Huntingdonshire',
    'Kent' => 'Kent',
    'Lancashire' => 'Lancashire',
    'Leicestershire' => 'Leicestershire',
    'Lincolnshire' => 'Lincolnshire',
    'Middlesex' => 'Middlesex',
    'Norfolk' => 'Norfolk',
    'North Yorkshire' => 'North Yorkshire',
    'Northamptonshire' => 'Northamptonshire',
    'Northumberland' => 'Northumberland',
    'Nottinghamshire' => 'Nottinghamshire',
    'Oxfordshire' => 'Oxfordshire',
    'Rutland' => 'Rutland',
    'Shropshire' => 'Shropshire',
    'Somerset' => 'Somerset',
    'Staffordshire' => 'Staffordshire',
    'Suffolk' => 'Suffolk',
    'Surrey' => 'Surrey',
    'Sussex' => 'Sussex',
    'Warwickshire' => 'Warwickshire',
    'West Yorkshire' => 'West Yorkshire',
    'Westmorland' => 'Westmorland',
    'Wiltshire' => 'Wiltshire',
    'Worcestershire' => 'Worcestershire',
    'Aberdeenshire' => 'Aberdeenshire',
    'Angus/Forfarshire' => 'Angus/Forfarshire',
    'Argyllshire' => 'Argyllshire',
    'Ayrshire' => 'Ayrshire',
    'Banffshire' => 'Banffshire',
    'Berwickshire' => 'Berwickshire',
    'Buteshire' => 'Buteshire',
    'Cromartyshire' => 'Cromartyshire',
    'Caithness' => 'Caithness',
    'Clackmannanshire' => 'Clackmannanshire',
    'Dumfriesshire' => 'Dumfriesshire',
    'Dunbartonshire/Dumbartonshire' => 'Dunbartonshire/Dumbartonshire',
    'East Lothian/Haddingtonshire' => 'East Lothian/Haddingtonshire',
    'Fife' => 'Fife',
    'Inverness-shire' => 'Inverness-shire',
    'Kincardineshire' => 'Kincardineshire',
    'Kinross-shire' => 'Kinross-shire',
    'Kirkcudbrightshire' => 'Kirkcudbrightshire',
    'Lanarkshire' => 'Lanarkshire',
    'Midlothian/Edinburghshire' => 'Midlothian/Edinburghshire',
    'Morayshire' => 'Morayshire',
    'Nairnshire' => 'Nairnshire',
    'Orkney' => 'Orkney',
    'Peeblesshire' => 'Peeblesshire',
    'Perthshire' => 'Perthshire',
    'Renfrewshire' => 'Renfrewshire',
    'Ross-shire' => 'Ross-shire',
    'Roxburghshire' => 'Roxburghshire',
    'Selkirkshire' => 'Selkirkshire',
    'Shetland' => 'Shetland',
    'Stirlingshire' => 'Stirlingshire',
    'Sutherland' => 'Sutherland',
    'West Lothian/Linlithgowshire' => 'West Lothian/Linlithgowshire',
    'Wigtownshire' => 'Wigtownshire',
    'Anglesey/Sir Fon' => 'Anglesey/Sir Fon',
    'Brecknockshire/Sir Frycheiniog' => 'Brecknockshire/Sir Frycheiniog',
    'Caernarfonshire/Sir Gaernarfon' => 'Caernarfonshire/Sir Gaernarfon',
    'Carmarthenshire/Sir Gaerfyrddin' => 'Carmarthenshire/Sir Gaerfyrddin',
    'Cardiganshire/Ceredigion' => 'Cardiganshire/Ceredigion',
    'Denbighshire/Sir Ddinbych' => 'Denbighshire/Sir Ddinbych',
    'Flintshire/Sir Fflint' => 'Flintshire/Sir Fflint',
    'Glamorgan/Morgannwg' => 'Glamorgan/Morgannwg',
    'Merioneth/Meirionnydd' => 'Merioneth/Meirionnydd',
    'Monmouthshire/Sir Fynwy' => 'Monmouthshire/Sir Fynwy',
    'Montgomeryshire/Sir Drefaldwyn' => 'Montgomeryshire/Sir Drefaldwyn',
    'Pembrokeshire/Sir Benfro' => 'Pembrokeshire/Sir Benfro',
    'Radnorshire/Sir Faesyfed' => 'Radnorshire/Sir Faesyfed',
    'County Antrim' => 'County Antrim',
    'County Armagh' => 'County Armagh',
    'County Down' => 'County Down',
    'County Fermanagh' => 'County Fermanagh',
    'County Tyrone' => 'County Tyrone',
    'County Londonderry/Derry' => 'County Londonderry/Derry',
);

foreach ($ukTowns as $ukTown) {
 
echo "<option value='$ukTown'";
 
	if ($record["ukTown"] == $ukTown) 
	{
	 	echo " selected='selected'";
	} 
 
echo ">$ukTown</option>";
 
}
 

?>